export const ADD_ITEM = 'ADD_ITEM';
export const REMOVER_ITEM = 'REMOVER_ITEM';
export const INCREMENTAR_QUANTIDADE_ITEM = 'INCREMENTAR_QUANTIDADE_ITEM';
export const DECREMENTAR_QUANTIDADE_ITEM = 'DECREMENTAR_QUANTIDADE_ITEM';
